### ISSUE TITLE
Remove the native dependency

### ISSUE THREAD

**Issue by tomfisher** [playn/playn#1]
We'd better drop the support for Android Froyo which is really outdated in the market so that the unnecessary native dependency could be removed.

**Comment by samskivert** [comment]
This is already done. The native dependency is gone in the new archetype, and the code that loads it in AndroidPlatform is also gone.

**Comment by tomfisher** [comment]
The jni folder is still there. 

BTW, shall we also do the same cleaning in PlayN1.9?

**Comment by samskivert** [comment]
Ah, I missed that jni cruft. It's gone now.

I'm not especially keen to remove the JNI stuff in PlayN 1.9 because there's no great reason to do so, and I'd rather not pull features out from under people who are using the old code base for whatever reason. If someone wants to support ancient Android devices, they can continue to use PlayN 1.9 to do so.
