### ISSUE TITLE
HTML hidpi mouse scaling issue (with fix)

### ISSUE THREAD

**Issue by kalimaul** [playn/playn#22]
When manually setting scaleFactor to 1 on a hidpi device (MacBook Pro Retina 2015), mouse input coordinates become broken. I found the reason for this in HtmlGraphics:

mouseScale = config.scaleFactor / HtmlPlatform.devicePixelRatio();

disabling this workaround (and setting mouseScale to 1) actually fixes my issue. However my game is using a custom scaling method to always fully occupy the available window/space so I'm not sure if that intereferes with this workaround.

If I don't change scaleFactor and leave it on its local default value of 2, then I have no problem with mouse coordinates.

Based on this it seems to me that this mouseScale workaround is unnecessary.

Tested on Google Chrome and Safari.

**Comment by samskivert** [comment]
Looking more deeply into the HiDPI support on the HTML backend, it's not doing what I intended, which is probably why it's broken.

If you are running on a HiDPI display that uses 2 real pixels for every "logical" pixel, then the default scale factor is 2. If you change that to 1, I want PlayN to make logical pixels equal to real pixels, so that you get a viewport that is 2x wider and 2x taller and then you can do what you want with all those pixels. But that's not what the HTML backend is doing right now. Instead it's just shrinking the framebuffer and then the web browser scales up that small framebuffer to fill the whole space and everything is blurry.

So I'll fix the HTML backend to do the "right" thing, and then maybe you can let me know if I've totally broken your use case. :)

**Comment by samskivert** [comment]
OK, I pushed the fix to the HTML backend. So now if you set scaleFactor to 1 in your HtmlPlatform.Config you get 1 logical pixel for 1 physical pixel (everything will look really small). The mouse scaling is necessary because in that mode, we're now "undoing" the HiDPI scaling that the browser naturally does.

Anyhow, give it a whirl and let me know if things make sense in this new setup. This should now mirror the behavior that would happen if you ran your game on the iOS backend and manually set the scaleFactor to 1.

I'm going to reintroduce a scale factor override to the Java backend (it now does the right thing with HiDPI displays by default but doesn't support overriding the scale factor), so then you should be able to see things behave the same way on Java, iOS and HTML when running on a Retina MacBook Pro.

**Comment by samskivert** [comment]
Oh, looking at the iOS backend, it looks like I nixed custom scale factor setting there too. It does get complicated to juggle the device scale factor and user scale factor along with all of the different things that each platform does to try to "hide" all the scale factor stuff from you. But I'll try to get that working too, so that we can test a "just give me all the pixels" mode on all the platforms that should ostensibly support it.

**Comment by kalimaul** [comment]
Hi, thanks for the update.
I originally wanted to change the scale factor for two reasons (both on hidpi devices):
- all textures created were 4x the size for no good reason (if the original image is the same size, upscaling it and putting it into a higher res texture seems pointless)
- rendering was slow on my MBP and the reason seemed to be fillrate related

In the previous versions, changing scaleFactor to 1 (and changing the mouse scale factor) fixed both of these (although you may not consider lower res rendering a fix, it solved the performance issue and the game looks fine regardless).

In the current version setting scaleFactor to 1 solves the texture size issue, but not the rendering/framebuffer size issue.

So I guess at this point I'm looking for a way to forcibly downscale the game's backing framebuffer to make rendering faster. Is there a way to do this?

**Comment by samskivert** [comment]
There isn't, but I can add it. More complexity! I'll look into how to do it without making things even more crazily complicated.

**Comment by kalimaul** [comment]
Thank you! I am grateful for you maintaining this project, it's an awesome tool. Since the last version of scaleFactor did exactly this, I'm hoping this is possible to implement as a small change :)

**Comment by samskivert** [comment]
OK, I added another configuration to HtmlPlatform.Config: `frameBufferPixelRatio`. By default that and `scaleFactor` are set to whatever the browser reports for the device pixel ratio (2 on HiDPI displays, 1 on normal displays).

You can change `scaleFactor` to 1 and leave `frameBufferPixelRatio` at the default to get a "raw" display where you get all the pixels and do what you want with them. Or you can set both of them to 1 to get a "normal" DPI display on both normal and HiDPI screens. On a HiDPI screen, the "normal" DPI frame buffer will be scaled up automatically by the web browser to fill the expected space, so it might be blurry, but it will use 1/4th the pixels.

**Comment by samskivert** [comment]
I'll look into replicating this level of control on the Java and iOS backends at some point.
